# Generated by Django 2.2.1 on 2019-06-01 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Communities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('author', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('irc_link', models.URLField()),
                ('community_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('venue', models.CharField(max_length=350)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('registration_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('logo', models.ImageField(upload_to='Source/logo/')),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('author', models.DateField()),
                ('published_date', models.DateField()),
                ('registration_link', models.URLField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='TutorialSource', to='Feed.Source')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('time', models.DateField(auto_now=True)),
                ('link', models.URLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='Post/')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='PostSource', to='Feed.Source')),
            ],
        ),
    ]
