# Generated by Django 2.2.1 on 2019-06-01 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Feed', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='registration_link',
            new_name='link',
        ),
    ]
