# Generated by Django 2.2.1 on 2019-06-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feed', '0005_auto_20190601_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='banner',
            field=models.ImageField(default='https://i.imgur.com/T8ylM8T.jpg', upload_to='Event/Banner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.CharField(default='Colombo Flutter Community', max_length=350),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='News/'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Widget/'),
        ),
    ]
